### ISSUE TITLE
Multi-thread support in Python bindings?

### ISSUE THREAD

**Issue by Sankgreall** [omerbenamram/pyevtx-rs#10]
I can see the binding is referencing the multi-threaded parameter, but seems to have no effect; just wondering if this is a planned feature or a bug that needs solving?

Really grateful you developed this btw - incredible tool, used every day!

**Comment by omerbenamram** [comment]
This seems to be a bug with the evtx library, where setting `num_threads` will only limit the number of concurrent chunks , not the size of the underlying thread pool.

https://github.com/omerbenamram/evtx/blob/master/src/evtx_parser.rs#L437

**Comment by jurelou** [comment]
That would be really nice !

**Comment by omerbenamram** [comment]
closed by #19
