### ISSUE TITLE
Request for Compiled Version (No matching distribution found for evtx==0.8.3)

### ISSUE THREAD

**Issue by yarden-nadav** [omerbenamram/pyevtx-rs#28]
I am currently attempting to install and use **evtx** on a Linux Arch-based system (Docker on Mac). Unfortunately, I have encountered an issue as there is no compiled version of the package available for the package.
I understand that maintaining compiled versions for various architectures can be challenging, but having support for the Linux Arch architecture would greatly benefit users in this environment.
Thank you for your attention to this matter.

**Comment by omerbenamram** [comment]
Hi,
the wheels uploaded are as extensive as python allows https://files.pythonhosted.org/packages/ec/5d/1383e37825606ce37e6b874926bb06966e56f7a6ea3fc892e92685c7139a/evtx-0.8.3-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

arch linux should be supported, if not, then maybe you are either using an old python version (<3.7) or some crazy old version of arch. maybe also update your version of `wheel` package.

**Comment by omerbenamram** [comment]
hi, CI indeed does not build aarch64 images for linux, only for mac, you can compile from sources if you'd like..

**Comment by omerbenamram** [comment]
pypi now has aarch64 links. https://files.pythonhosted.org/packages/03/61/230fc0003360f4ef927673d2a45033718026f0ed4e22992628b600505991/evtx-0.8.3-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
