### ISSUE TITLE
InstanceID missing from logs

### ISSUE THREAD

**Issue by truekonrads** [omerbenamram/pyevtx-rs#9]
Evtx'es have a property "InstanceID" which is related to EventID:

> InstanceID is not EventID, but can be:
> The InstanceId property uniquely identifies an event entry for a configured event source. The InstanceId for an event log entry represents the full 32-bit resource identifier for the event in the message resource file for the event source. The EventID property equals the InstanceId with the top two bits masked off. Two event log entries from the same source can have matching EventID values, but have different InstanceId values due to differences in the top two bits of the resource identifier. If the application wrote the event entry using one of the WriteEntry methods, the InstanceId property matches the optional eventId parameter. If the application wrote the event using WriteEvent, the InstanceId property matches the resource identifier specified in the InstanceId of the instance parameter. If the application wrote the event using the Win32 API ReportEvent, the InstanceId property matches the resource identifier specified in the dwEventID parameter.

Taken from here: https://evotec.xyz/powershell-everything-you-wanted-to-know-about-event-logs/

I would very much like to have InstanceID read in. It isn't in the XML data; XML data contains EventID

I don't know enough about evtx structure to offer a patch.

**Comment by omerbenamram** [comment]
This might be related to `https://github.com/omerbenamram/evtx` - but this repo contains only python bindings.

**Comment by truekonrads** [comment]
I added an issue here: https://github.com/omerbenamram/pyevtx-rs/issues/9
